NeXus type hardening
cctbx/dxtbx pull request #252
Opened 2020-11-09 15:27 UTC by graeme-winter

- If scalar, don't fail
- Cast to numpy str for comparison

2020-11-09 15:47 UTC, graeme-winter commented
Reviewing in light of test failures now

2020-11-09 15:55 UTC, benjaminhwilliams requested changes
If the values are always guaranteed to be numbers, I think my suggestion is safe.

2020-11-09 15:55 UTC, benjaminhwilliams commented on format/nexus.py
>                      is_scan_axis = False
I suggest this, which is safe if your dataset is scalar or iterable:
```suggestion
                v = item[...]
                if v.min() < v.max():
                    is_scan_axis = True
                else:
                    is_scan_axis = False
```

2020-11-09 15:55 UTC, benjaminhwilliams commented on format/nexus.py
>              v = o[()]
```suggestion
            v = o[...]
```

2020-11-09 15:55 UTC, benjaminhwilliams commented on format/nexus.py
> +                continue
```suggestion
            if v.min() < v.max():
                return o
```

2020-12-18 11:22 UTC, ndevenish commented
Updated to resolve conflicts. Since #263 was merged into master, "Cast to numpy str for comparison" is no longer relevant.

2020-12-18 19:16 UTC, merged