Move dxtbx to src/ layout
cctbx/dxtbx pull request #382
Opened 2021-06-11 18:15 UTC by ndevenish

An embedded layout (e.g. at least in a subfolder to the root) is a requirement for moving dxtbx towards being a relatively normal installable package. `src/` layout provides isolation against namespace contamination with the other folders in the package root - both for headers, and `PYTHONPATH` purposes.

- Updated SConscript to retain identical build behaviour and provide include paths to the new location
- Created setup.py to (editable or otherwise) install the dxtbx library into an existing environment. It generates the list of console_scripts entry points and Format registry entry points automatically. I've tried to keep the actual `setup.py` somewhat plain, and moved the dynamic logic into a `build.py` file
- Modified libtbx_refresh.py to editable-install the dxtbx package when configured as part of a libtbx environment

A possible... complication, is that it appears that the general "generate console_scripts entrypoints as libtbx dispatchers" behaviour appears to be somewhat related to calling `libtbx.pkg_utils.define_entry_points`. At least, the dispatchers for things like `bin/pytest` have disappeared on my environments. Not sure how to work around that?

2021-06-11 21:38 UTC, Anthchirp commented
This will need some rigorous testing. One to discuss next Thursday, I assume.

> A possible... complication, is that it appears that the general "generate console_scripts entrypoints as libtbx dispatchers" behaviour appears to be somewhat related to calling `libtbx.pkg_utils.define_entry_points`. At least, the dispatchers for things like bin/pytest have disappeared on my environments. Not sure how to work around that?

No, libtbx is fine as it is.

The `bin/pytest` dispatcher disappeared because it was generated via `dxtbx` (in [`command_line/pytest_launcher.py`](https://github.com/cctbx/dxtbx/blob/main/command_line/pytest_launcher.py)). In libtbx *tbx packages are evaluated differently from python packages: Any libtbx `command_line/` script will only get an 'outer' dispatcher generated in `/build/bin`, whereas a python package `console_scripts` entry point will get the regular 'inner' python dispatcher underneath `/base` (not controlled or affected by libtbx), and nothing in `/build`.
The problem is then that anything launched from a regular python dispatcher will not be able to import anything from underneath the `modules/` directory (unless installed as python package with `pip -e`), and certainly not any external modules from the `/build` directory - which meant that the regular `pytest` dispatcher was unable to test eg. `dxtbx`.

By transforming dxtbx into a standard python module you implicitly removed the `build/bin` dispatchers, which I guess is also the cause for the build errors you can see on Azure.

So how can you fix this? It should be relatively easy. Tell libtbx to generate an additional outer dispatcher for the inner dispatcher. Set entry points `libtbx.dispatcher.script` with `OUTER=INNER` where OUTER is the name of the outer dispatcher and INNER the name of the inner dispatcher.
Once you know what to look for you'll find this pattern all over the place in more or less all our packages:
* [fastdp](https://github.com/DiamondLightSource/fast_dp/blob/a976d8c9dc8ef499fb985a6947ae25ed5a000263/setup.py#L27)
* [dlstbx](https://github.com/DiamondLightSource/python-dlstbx/blob/915df5d3c261c27e7910ec698e524e446b303d9e/setup.py#L169-L172)
* [ispyb-api](https://github.com/DiamondLightSource/ispyb-api/blob/903a9eb0836e985a341df613d7c8743b76401f90/setup.cfg#L50-L52)
* [zocalo](https://github.com/DiamondLightSource/python-zocalo/blob/c93a5b8a019aa95c2e5d5cda23ddbf03b6990efa/setup.cfg#L45-L48)
* [xia2](https://github.com/xia2/xia2/blob/1838cdce46512afe2692b7f0da6a8e200ae50b45/setup.py#L96-L98)
* ...

While you're there - could you please also add an entry point `libtbx.precommit: "dxtbx=dxtbx"`? This will ensure pre-commits will installed automatically on the repository if it sits underneath `modules/`. Purely for the benefit of those of us who don't have it set up globally.

2021-06-15 18:06 UTC, ndevenish commented
I suspect most of these errors now are due to https://github.com/cctbx/dxtbx/issues/383

2021-06-17 20:03 UTC, Anthchirp requested changes

2021-06-17 20:03 UTC, Anthchirp commented on build.py
> +    console_scripts.extend([x for x in all_dispatchers if x not in console_scripts])
```suggestion
    console_scripts.extend(x for x in all_dispatchers if x not in console_scripts)
    libtbx_dispatchers = entry_points.setdefault("libtbx.dispatcher.script", [])
    libtbx_dispatchers.extend("{name}={name}".format(name=x.split("=")[0]) for x in console_scripts)
```

2021-06-18 11:19 UTC, ndevenish commented
So, I've put it back in, but only if it is already installed (or it can't tell). I think that's possibly cleaner than continuing to install it into new environments.

2021-06-18 11:54 UTC, ndevenish commented
CCTBX bootstrap for `--builder=xfel` and `--builder=phenix` both build fine (to a point - the phenix builder didn't download phenix or boost, so either broken or not the normal way).

Running libtbx.refresh with the new changes seem to run into:
```
Traceback (most recent call last):
  File "/tmp/mep23677/dist_dials/modules/cctbx_project/libtbx/env_config.py", line 3200, in <module>
    unpickle().refresh()
  File "/tmp/mep23677/dist_dials/modules/cctbx_project/libtbx/env_config.py", line 2249, in refresh
    self.generate_entry_point_dispatchers()
  File "/tmp/mep23677/dist_dials/modules/cctbx_project/libtbx/env_config.py", line 2123, in generate_entry_point_dispatchers
    self.write_dispatcher(
  File "/tmp/mep23677/dist_dials/modules/cctbx_project/libtbx/env_config.py", line 1640, in write_dispatcher
    raise RuntimeError("Multiple sources for dispatcher:\n"
RuntimeError: Multiple sources for dispatcher:
  target file:
    "/tmp/mep23677/dist_dials/build/bin/cxi.image2pickle"
  source files:
    "/tmp/mep23677/dist_dials/modules/dxtbx/src/dxtbx/command_line/image2pickle.py"
   =relocatable_path(anchor="/tmp/mep23677/dist_dials/build", relocatable="../modules/dxtbx/src/dxtbx/command_line/image2pickle.py")
    "/tmp/mep23677/dist_dials/conda_base/bin/cxi.image2pickle"
   =relocatable_path(anchor="/tmp/mep23677/dist_dials/build", relocatable="../conda_base/bin/cxi.image2pickle")
```

2021-06-18 12:27 UTC, Anthchirp commented
> So, I've put it back in, but only if it is already installed (or it can't tell). I think that's possibly cleaner than continuing to install it into new environments.

More effort than what I'd have put in for something that will be removed anyway :shrug: 

The error is not that surprising - for some reason you explicitly tell libtbx to generate dispatchers for the `src/dxtbx/command_line` directory in `libtbx_config`. Those will of course conflict with the ones you tell it to generate via the `libtbx.dispatcher.script` entry point.

To be honest, I would suggest completely eliminating the `command_line` directory, rather than keeping it around and half-depending on libtbx-like mechanisms. That is the approach we took when we implemented DC1 for xia2 (xia2/xia2#528) and I think that was the correct choice.

2021-06-18 14:33 UTC, Anthchirp approved these changes
Haven't tested the upgrade paths, but bootstrapping looks good to me

2021-06-18 14:58 UTC, ndevenish commented
I'm just trying on a very old distribution on my old mac. It's rather slow to rebuild everything though...

2021-06-18 18:26 UTC, ndevenish commented
This worked fine. It did need _three_ `libtbx.refresh` for an existing (old) installation. This appears to somewhat be similar to the pattern:
1. No dispatchers are removed, the metapackage is updated to be empty, and dxtbx package installed. The registry doesn't work.
2. The dispatchers are removed, since the metapackage has been removed.
3. The new dispatchers are installed.

I think this comes from the limitation that a packages dispatchers are handled _before_ we can fiddle with entry_points in `libtbx_refresh`. It's a bit annoying, but leaves us in a better place, and new(er?) installs are unaffected.

2021-06-21 14:16 UTC, ndevenish commented
Okay, so the plan was to merge this, and patch the new dxtbx include path into the dials include path temporarily. Except that won't work because xfel recalculates the dials path: https://github.com/cctbx/cctbx_project/blob/8a572444f4c6e6787c6fd4af2fa1569adc331d9b/xfel/SConscript#L7-L8.

So I'm going to leave this here until cctbx-base 2021.6 is release, which should hopefully be around beginning of... july

2021-07-05 15:33 UTC, merged