dxtbx.plot_detector_models fixes for multiple single-panel detector models
cctbx/dxtbx pull request #610
Opened 2023-02-17 12:21 UTC by rjgildea

* Only create a new axis once, therwise for additional detector models we create a new subplot on top of the existing ones. See also #574.
* Use all panel corners to determine z-range, not just the panel origin. Possibly mainly an issue for display of single-panel detectors. See also #476.

With current `main`:
![Screenshot 2023-02-17 at 13 04 32](https://user-images.githubusercontent.com/2810624/219660914-254f5899-3a6e-470e-ab4d-6f3c49173258.png)
With 1387211:
![Screenshot 2023-02-17 at 13 05 24](https://user-images.githubusercontent.com/2810624/219661045-080a836a-f42a-41f4-bb36-27da3329d5a4.png)
With ec5b721:
![Screenshot 2023-02-17 at 13 06 11](https://user-images.githubusercontent.com/2810624/219661102-0e2154e7-deee-4876-a3c8-c9a70411e131.png)

2023-02-23 16:12 UTC, ndevenish requested changes
Causing CSPad plotting failures

2023-02-23 16:40 UTC, rjgildea commented
> Causing CSPad plotting failures

Could we have a reproducer?

2023-02-23 16:46 UTC, phyy-nx commented
Hi, here it is:

```
dials.data get lysozyme_JF16M_4img
(cd to that folder)
dxtbx.plot_detector_models lyso009a_0087.JF07T32V01_master_4img_imported.expt
```

Works on master, fails on main

2023-03-01 13:57 UTC, rjgildea commented
```
$ dxtbx.plot_detector_models $(dials.data get -q lysozyme_JF16M_4img)/lyso009a_0087.JF07T32V01_master_4img_imported.expt show_origin_vectors=False panel_numbers=False
```
now gives:
<img width="720" alt="Screenshot 2023-03-01 at 13 54 24" src="https://user-images.githubusercontent.com/2810624/222161111-9dda35a6-7ed2-46f4-b7c4-0f706e6e6c14.png">

2023-03-09 23:48 UTC, phyy-nx approved these changes
Works for me.  Thanks.

2023-03-10 10:33 UTC, merged