Add probe type to the Beam model
cctbx/dxtbx pull request #647
Opened 2023-07-24 15:32 UTC by dagewa

Fixes [#575](https://github.com/cctbx/dxtbx/issues/575).

This PR adds a `Probe` `enum` to `Beam`. In future this could be used to alter behaviour of algorithms, such as the QE and parallax corrections. At the moment this just adds the additional datum and allows serialisation etc. Old experiment files where this is not set are interpreted as having `Probe.xray`. Some electron diffraction format classes are updated here to record `Probe.electron`.

A DIALS PR will be required following this. Currently the only DIALS tests that fail are those for `dials.show`.

2023-08-02 07:52 UTC, toastisme approved these changes
This all looks fine to me, and should be quite useful.

2023-08-02 16:46 UTC, dagewa commented
@toastisme I've made the changes to hopefully get `Probe` working with the `PolychromaticBeam`. Might have missed something, so if you have anything else you can check on your fork that would be good. One thing I wasn't sure of were the type hints for a value like `Probe.xray`, so I just left that blank.

2023-08-03 13:59 UTC, toastisme commented
> @toastisme I've made the changes to hopefully get `Probe` working with the `PolychromaticBeam`. Might have missed something, so if you have anything else you can check on your fork that would be good. One thing I wasn't sure of were the type hints for a value like `Probe.xray`, so I just left that blank.

Had a look and looks good. I realised `Probe` wasn't part of the phil params so have added it [here](https://github.com/cctbx/dxtbx/pull/654), along with a suggestion to have the probe be the NeXus name in .expt files, rather than the enum int, to make it human readable.

2023-08-04 13:21 UTC, ndevenish requested changes

2023-08-04 13:21 UTC, ndevenish commented on src/dxtbx/model/beam.h
> +        return std::string("unknown");
```suggestion
        DXTBX_ERROR("Unknown probe type");
```

2023-08-04 13:21 UTC, ndevenish commented on src/dxtbx/model/beam.h
> +      return Probe::xray;
```suggestion
      DXTBX_ERROR("Unknown probe " + probe);
```

Top line throws, right?

2023-08-04 15:47 UTC, ndevenish approved these changes

2023-08-04 15:48 UTC, merged